# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Live Wallpapers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.0'
  # Pods for Live Wallpapers

end
